{
    "openapi": "3.0.0",
    "paths": {
        "/": {
            "get": {
                "operationId": "AppController_getHello",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": ""
                    }
                },
                "tags": [
                    "App"
                ]
            }
        },
        "/auth/request": {
            "post": {
                "operationId": "AuthController_requestOtp",
                "parameters": [],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/RequestOtpDto"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OTP sent successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "OTP sent successfully",
                                    "email": "chuksaginamada@gmail.com"
                                }
                            }
                        }
                    }
                },
                "summary": "Request OTP for signup/signin",
                "tags": [
                    "Auth"
                ]
            }
        },
        "/auth/verify": {
            "post": {
                "operationId": "AuthController_verifyOtp",
                "parameters": [],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/VerifyOtpDto"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OTP verified successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "message": "Authentication successful",
                                    "user": {
                                        "_id": "68f8d5eb71ee81dd785a2f6f",
                                        "username": "frozen_moon_0",
                                        "email": "chuksaginamada@gmail.com",
                                        "role": "developer",
                                        "walletAddress": null,
                                        "balance": 0,
                                        "createdAt": "2025-10-22T13:02:35.951Z",
                                        "updatedAt": "2025-10-22T13:32:27.830Z",
                                        "id": "68f8d5eb71ee81dd785a2f6f"
                                    },
                                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGY4ZDVlYjcxZWU4MWRkNzg1YTJmNmYiLCJpYXQiOjE3NjExOTkzNjUsImV4cCI6MTc2MTIwMjk2NX0.KeWvYv1vL-4ej4Ov4XvezpCEOnjFiAlSOINU6LpN8Dg"
                                }
                            }
                        }
                    }
                },
                "summary": "Verify OTP to complete login/signup",
                "tags": [
                    "Auth"
                ]
            }
        },
        "/user/me": {
            "get": {
                "operationId": "UserController_me",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "Loggedin user data fetched successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "_id": "68f8d5eb71ee81dd785a2f6f",
                                        "username": "frozen_moon_0",
                                        "email": "chuksaginamada@gmail.com",
                                        "role": "developer",
                                        "walletAddress": null,
                                        "balance": 0,
                                        "createdAt": "2025-10-22T13:02:35.951Z",
                                        "updatedAt": "2025-10-22T13:32:27.830Z",
                                        "id": "68f8d5eb71ee81dd785a2f6f"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Fetch loggedin user",
                "tags": [
                    "User"
                ]
            }
        },
        "/user/upgrade": {
            "patch": {
                "operationId": "UserController_upgradeToDeveloper",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "User successfully upgraded to developer",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "User upgraded to developer successfully",
                                        "role": "developer"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "User is already a developer",
                        "content": {
                            "application/json": {
                                "example": {
                                    "statusCode": 400,
                                    "message": "User is already a developer",
                                    "timestamp": "2025-10-23T06:07:26.627Z",
                                    "path": "/user/upgrade"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Upgrade user to developer account",
                "tags": [
                    "User"
                ]
            }
        },
        "/otp/send": {
            "post": {
                "operationId": "OtpController_sendOtp",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "OTP sent successfully.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "OTP sent successfully",
                                        "email": "user@example.com"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Send an OTP to an email",
                "tags": [
                    "OTP"
                ]
            }
        },
        "/game/genre/create": {
            "post": {
                "operationId": "GameGenreController_createGenre",
                "parameters": [],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateGenreDto"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Genre created successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Genre created",
                                        "genre": {
                                            "genre": "action",
                                            "_id": "68f9c676fa4b381c1f14a47d",
                                            "createdAt": "2025-10-23T06:08:54.557Z",
                                            "id": "68f9c676fa4b381c1f14a47d"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Create a new game genre",
                "tags": [
                    "Game Genre"
                ]
            }
        },
        "/game/genre/all": {
            "get": {
                "operationId": "GameGenreController_fetchAllGenres",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "List of genres fetched successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Genres fetched successfully",
                                        "genres": [
                                            {
                                                "_id": "68f9c676fa4b381c1f14a47d",
                                                "genre": "action",
                                                "id": "68f9c676fa4b381c1f14a47d"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Fetch all game genres",
                "tags": [
                    "Game Genre"
                ]
            }
        },
        "/game/create": {
            "post": {
                "operationId": "GameController_createGame",
                "parameters": [],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateGameDto"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Game created successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Game created successfully",
                                        "game": {
                                            "_id": "68f9cab3ab7bb4057203f470",
                                            "name": "Battle Arena",
                                            "banner": "https://cdn.com/game-banner.jpg",
                                            "description": "An intense multiplayer battle arena game.",
                                            "website": "https://game-website.com",
                                            "genre": [
                                                {
                                                    "_id": "68f9c676fa4b381c1f14a47d",
                                                    "genre": "action",
                                                    "id": "68f9c676fa4b381c1f14a47d"
                                                }
                                            ],
                                            "tags": [
                                                "action",
                                                "multiplayer"
                                            ],
                                            "isActive": true,
                                            "createdAt": "2025-10-23T06:26:59.642Z",
                                            "slug": "battle-arena",
                                            "apiKey": "nexra_e738a4f246da347b1a7696c5d1279c1d",
                                            "id": "68f9cab3ab7bb4057203f470"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Create a new game",
                "tags": [
                    "Game"
                ]
            }
        },
        "/game/{gameId}/update": {
            "patch": {
                "operationId": "GameController_updateGame",
                "parameters": [
                    {
                        "name": "gameId",
                        "required": true,
                        "in": "path",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UpdateGameDto"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Game updated successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Game updated successfully",
                                        "game": {
                                            "_id": "68f9cb7995b222b91665469c",
                                            "name": "Battle Arena2",
                                            "banner": "https://cdn.com/game-banner.jpg",
                                            "description": "An intense multiplayer battle arena game.",
                                            "website": "https://game-website.com",
                                            "genre": [
                                                {
                                                    "_id": "68f9c676fa4b381c1f14a47d",
                                                    "genre": "action",
                                                    "id": "68f9c676fa4b381c1f14a47d"
                                                }
                                            ],
                                            "tags": [
                                                "action",
                                                "multiplayer"
                                            ],
                                            "isActive": true,
                                            "createdAt": "2025-10-23T06:30:17.149Z",
                                            "slug": "battle-arena",
                                            "id": "68f9cb7995b222b91665469c"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Update a game",
                "tags": [
                    "Game"
                ]
            }
        },
        "/game/my": {
            "get": {
                "operationId": "GameController_fetchUserGames",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "List of user games fetched successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "List of user games fetched successfully",
                                        "games": [
                                            {
                                                "_id": "68f9cb7995b222b91665469c",
                                                "name": "Battle Arena2",
                                                "banner": "https://cdn.com/game-banner.jpg",
                                                "description": "An intense multiplayer battle arena game.",
                                                "website": "https://game-website.com",
                                                "genre": [
                                                    "68f9c676fa4b381c1f14a47d"
                                                ],
                                                "tags": [
                                                    "action",
                                                    "multiplayer"
                                                ],
                                                "developer": "68f8d5eb71ee81dd785a2f6f",
                                                "isActive": true,
                                                "createdAt": "2025-10-23T06:30:17.149Z",
                                                "updatedAt": "2025-10-23T06:34:06.654Z",
                                                "slug": "battle-arena",
                                                "id": "68f9cb7995b222b91665469c"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Fetch all games created by logged-in user",
                "tags": [
                    "Game"
                ]
            }
        },
        "/game/{gameId}/view-apikey": {
            "post": {
                "operationId": "GameController_viewApiKey",
                "parameters": [
                    {
                        "name": "id",
                        "required": true,
                        "in": "path",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ApikeyDto"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "API key fetched successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "API key fetched successfully",
                                        "result": {
                                            "apiKey": "nexra_78629bc0147e655599706188aacb0c48"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "View game API key (OTP required)",
                "tags": [
                    "Game"
                ]
            }
        },
        "/game/{gameId}/regenerate-apikey": {
            "patch": {
                "operationId": "GameController_regenerateApiKey",
                "parameters": [
                    {
                        "name": "id",
                        "required": true,
                        "in": "path",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ApikeyDto"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "API key fetched successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "API key regenerated successfully",
                                        "result": {
                                            "apiKey": "nexra_abea6077b25d793f1e8b6ff2e48d5f08"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Regenerate game API key (OTP required)",
                "tags": [
                    "Game"
                ]
            }
        },
        "/tournament/create": {
            "post": {
                "operationId": "TournamentController_create",
                "parameters": [],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateTournamentDto"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Tournament created successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "schema": {
                                        "message": "Tournament created successfully",
                                        "tournament": {
                                            "game": {
                                                "_id": "68f9ce6d27a07cdb23dd65c7",
                                                "name": "Battle Arenaa",
                                                "id": "68f9ce6d27a07cdb23dd65c7"
                                            },
                                            "name": "Battle of Nexra",
                                            "description": "An intense tournament for top gamers",
                                            "entryFee": 50,
                                            "prizePool": 0,
                                            "status": "pending",
                                            "startTime": "2025-11-10T18:00:00.000Z",
                                            "endTime": "2025-11-10T21:00:00.000Z",
                                            "winner": null,
                                            "_id": "68fa2b750366dd5ff66d599d",
                                            "createdAt": "2025-10-23T13:19:49.620Z",
                                            "updatedAt": "2025-10-23T13:19:49.620Z",
                                            "id": "68fa2b750366dd5ff66d599d"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Create a tournament",
                "tags": [
                    "Tournaments"
                ]
            }
        },
        "/tournament/{tournamentId}/update": {
            "patch": {
                "operationId": "TournamentController_update",
                "parameters": [
                    {
                        "name": "tournamentIdupdate",
                        "required": true,
                        "in": "path",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UpdateTournamentDto"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Tournament updated successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "schema": {
                                        "message": "Tournament updated successfully",
                                        "tournament": {
                                            "_id": "68fa2b750366dd5ff66d599d",
                                            "game": {
                                                "_id": "68f9ce6d27a07cdb23dd65c7",
                                                "name": "Battle Arenaa",
                                                "id": "68f9ce6d27a07cdb23dd65c7"
                                            },
                                            "name": "Battle of Nexra",
                                            "description": "An intense tournament for top gamers",
                                            "entryFee": 50,
                                            "prizePool": 0,
                                            "status": "pending",
                                            "startTime": "2025-11-10T18:00:00.000Z",
                                            "endTime": "2025-11-10T21:00:00.000Z",
                                            "winner": null,
                                            "createdAt": "2025-10-23T13:19:49.620Z",
                                            "updatedAt": "2025-10-23T13:19:49.620Z",
                                            "id": "68fa2b750366dd5ff66d599d"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Update a pending tournament (if not started)",
                "tags": [
                    "Tournaments"
                ]
            }
        },
        "/tournament/{tournamentIdupdate}/publish": {
            "patch": {
                "operationId": "TournamentController_publish",
                "parameters": [
                    {
                        "name": "id",
                        "required": true,
                        "in": "path",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tournament published successfully",
                        "content": {
                            "application/json": {
                                "example": {
                                    "schema": {
                                        "message": "Tournament published successfully",
                                        "tournament": {
                                            "_id": "68fa2b750366dd5ff66d599d",
                                            "game": {
                                                "_id": "68f9ce6d27a07cdb23dd65c7",
                                                "name": "Battle Arenaa",
                                                "id": "68f9ce6d27a07cdb23dd65c7"
                                            },
                                            "name": "Battle of Nexra",
                                            "description": "An intense tournament for top gamers",
                                            "entryFee": 50,
                                            "prizePool": 0,
                                            "status": "published",
                                            "startTime": "2025-11-10T18:00:00.000Z",
                                            "endTime": "2025-11-10T21:00:00.000Z",
                                            "winner": null,
                                            "createdAt": "2025-10-23T13:19:49.620Z",
                                            "updatedAt": "2025-10-23T13:42:12.609Z",
                                            "id": "68fa2b750366dd5ff66d599d"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Publish a pending tournament that has not yet started",
                "tags": [
                    "Tournaments"
                ]
            }
        },
        "/tournament/{tournamentId}/join": {
            "post": {
                "description": "Creates a gamer if not existing, adds them to the tournament, creates their bet option, and updates the prize pool.",
                "operationId": "TournamentController_joinTournament",
                "parameters": [
                    {
                        "name": "tournamentId",
                        "required": true,
                        "in": "path",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateTournamentEntryDto"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Successfully joined the tournament.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Gamer successfully joined the tournament.",
                                        "entry": {
                                            "id": "6718ac03e0ad9b01f43b76b3",
                                            "tournament": "6718a8dde0ad9b01f43b76a2",
                                            "gamer": "6718ab5ee0ad9b01f43b76a8",
                                            "entryFee": 100,
                                            "joinedAt": "2025-10-23T13:25:48.112Z",
                                            "eliminated": false,
                                            "eliminatedAt": null,
                                            "rank": null,
                                            "createdAt": "2025-10-23T13:25:48.112Z",
                                            "updatedAt": "2025-10-23T13:25:48.112Z"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Enter a gamer into a tournament",
                "tags": [
                    "Tournaments"
                ]
            }
        },
        "/prediction/predict": {
            "post": {
                "description": "Allows a user to place a prediction and updates the total amount in the related prediction option.",
                "operationId": "PredictionController_makePrediction",
                "parameters": [],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreatePredictionDto"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Prediction placed successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "message": "Prediction placed successfully",
                                        "prediction": {
                                            "_id": "68fcc01bb3315090e6bb4cf8",
                                            "bettor": "68f8d5eb71ee81dd785a2f6f",
                                            "predictionOption": {
                                                "_id": "68fcbfeeb3315090e6bb4cf1",
                                                "tournament": {
                                                    "_id": "68fa2dbd186115a612e75e13",
                                                    "name": "Battle of Nexra2",
                                                    "description": "An intense tournament for top gamers",
                                                    "totalPredictionAmount": 250,
                                                    "id": "68fa2dbd186115a612e75e13"
                                                },
                                                "gamer": {
                                                    "_id": "68fcbfeeb3315090e6bb4cea",
                                                    "gamerId": "dark gamer",
                                                    "id": "68fcbfeeb3315090e6bb4cea"
                                                },
                                                "totalPredictionAmount": 50,
                                                "odds": 5,
                                                "id": "68fcbfeeb3315090e6bb4cf1"
                                            },
                                            "amount": 50,
                                            "oddsAtPlacement": 200,
                                            "status": "pending",
                                            "createdAt": "2025-10-25T12:18:35.482Z",
                                            "id": "68fcc01bb3315090e6bb4cf8",
                                            "potentialPayout": 250
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "jwt-auth": []
                    }
                ],
                "summary": "Place a prediction",
                "tags": [
                    "Prediction"
                ]
            }
        }
    },
    "info": {
        "title": "Nexrahub Core API Documentation",
        "description": "API documentation for Nexrahub Core services",
        "version": "1.0.0",
        "contact": {}
    },
    "tags": [],
    "servers": [
        {
            "url": "http://localhost:9871/",
            "description": "Local environment"
        }
    ],
    "components": {
        "securitySchemes": {
            "jwt-auth": {
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "type": "http",
                "name": "Authorization",
                "in": "header"
            }
        },
        "schemas": {
            "RequestOtpDto": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string",
                        "example": "chuksaginamada@gmail.com",
                        "description": "User email"
                    }
                },
                "required": [
                    "email"
                ]
            },
            "VerifyOtpDto": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string",
                        "example": "chuksaginamada@gmail.com",
                        "description": "User email"
                    },
                    "code": {
                        "type": "string",
                        "example": "123456",
                        "description": "OTP code"
                    }
                },
                "required": [
                    "email",
                    "code"
                ]
            },
            "CreateGenreDto": {
                "type": "object",
                "properties": {
                    "genre": {
                        "type": "string",
                        "example": "Action",
                        "description": "Genre name"
                    }
                },
                "required": [
                    "genre"
                ]
            },
            "CreateGameDto": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "example": "Battle Arena",
                        "description": "Name of the game"
                    },
                    "description": {
                        "type": "string",
                        "example": "An intense multiplayer battle arena game.",
                        "description": "Description of the game"
                    },
                    "website": {
                        "type": "string",
                        "example": "https://game-website.com",
                        "description": "Official website of the game"
                    },
                    "banner": {
                        "type": "string",
                        "example": "https://cdn.com/game-banner.jpg",
                        "description": "Banner image URL for the game"
                    },
                    "genre": {
                        "example": [
                            "6716a5097b6a0b214b9de701"
                        ],
                        "description": "Genre ID",
                        "type": "array",
                        "items": {
                            "type": "array"
                        }
                    },
                    "tags": {
                        "example": [
                            "action",
                            "multiplayer"
                        ],
                        "description": "Tags associated with the game",
                        "type": "array",
                        "items": {
                            "type": "array"
                        }
                    }
                },
                "required": [
                    "name",
                    "description",
                    "website",
                    "banner",
                    "genre"
                ]
            },
            "UpdateGameDto": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "example": "Battle Arena",
                        "description": "Name of the game"
                    },
                    "description": {
                        "type": "string",
                        "example": "An intense multiplayer battle arena game.",
                        "description": "Description of the game"
                    },
                    "website": {
                        "type": "string",
                        "example": "https://game-website.com",
                        "description": "Official website of the game"
                    },
                    "banner": {
                        "type": "string",
                        "example": "https://cdn.com/game-banner.jpg",
                        "description": "Banner image URL for the game"
                    },
                    "genre": {
                        "example": [
                            "6716a5097b6a0b214b9de701"
                        ],
                        "description": "Genre ID",
                        "type": "array",
                        "items": {
                            "type": "array"
                        }
                    },
                    "tags": {
                        "example": [
                            "action",
                            "multiplayer"
                        ],
                        "description": "Tags associated with the game",
                        "type": "array",
                        "items": {
                            "type": "array"
                        }
                    }
                }
            },
            "ApikeyDto": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "string",
                        "example": "123456",
                        "description": "OTP code"
                    }
                },
                "required": [
                    "code"
                ]
            },
            "CreateTournamentDto": {
                "type": "object",
                "properties": {
                    "game": {
                        "type": "string",
                        "description": "Game ID",
                        "example": "67188e92b41c0eec54f22b1f"
                    },
                    "name": {
                        "type": "string",
                        "example": "Battle of Nexra",
                        "description": "Tournament name"
                    },
                    "description": {
                        "type": "string",
                        "example": "An intense tournament for top gamers",
                        "description": "Tournament description"
                    },
                    "entryFee": {
                        "type": "number",
                        "example": 50,
                        "description": "Gamers entry fee for the tournament"
                    },
                    "startTime": {
                        "format": "date-time",
                        "type": "string",
                        "example": "2025-11-10T18:00:00Z",
                        "description": "Tournament start time"
                    },
                    "endTime": {
                        "format": "date-time",
                        "type": "string",
                        "example": "2025-11-10T21:00:00Z",
                        "description": "Tournament end time"
                    }
                },
                "required": [
                    "game",
                    "name"
                ]
            },
            "UpdateTournamentDto": {
                "type": "object",
                "properties": {
                    "game": {
                        "type": "string",
                        "description": "Game ID",
                        "example": "67188e92b41c0eec54f22b1f"
                    },
                    "name": {
                        "type": "string",
                        "example": "Battle of Nexra",
                        "description": "Tournament name"
                    },
                    "description": {
                        "type": "string",
                        "example": "An intense tournament for top gamers",
                        "description": "Tournament description"
                    },
                    "entryFee": {
                        "type": "number",
                        "example": 50,
                        "description": "Gamers entry fee for the tournament"
                    },
                    "startTime": {
                        "format": "date-time",
                        "type": "string",
                        "example": "2025-11-10T18:00:00Z",
                        "description": "Tournament start time"
                    },
                    "endTime": {
                        "format": "date-time",
                        "type": "string",
                        "example": "2025-11-10T21:00:00Z",
                        "description": "Tournament end time"
                    }
                }
            },
            "CreateTournamentEntryDto": {
                "type": "object",
                "properties": {
                    "gamer": {
                        "type": "string",
                        "description": "Gamer ID",
                        "example": "silent gamer"
                    }
                },
                "required": [
                    "gamer"
                ]
            },
            "CreatePredictionDto": {
                "type": "object",
                "properties": {
                    "predictionOption": {
                        "type": "string",
                        "example": "6718b9f9e72b3b298a1fc025",
                        "description": "Prediction option ID"
                    },
                    "amount": {
                        "type": "number",
                        "example": 150,
                        "description": "Amount to bet (minimum 1)"
                    }
                },
                "required": [
                    "predictionOption",
                    "amount"
                ]
            }
        }
    }
}